language: node_js

node_js:
  - '12'

cache:
  npm: false

branches:
  only:
  - master
  - /((release|hotfix|feature)\/.*)/

script:
  - npm test

after_success:
  - mv .env.production .env
  - chmod 0777 bin/deployment.sh
  - ./bin/deployment.sh

notifications:
  email:
    on_success: never
    on_failure: always