service: jsdailybot

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 256
  timeout: 30
  environment:
    SLS_DEBUG: '*'
    TWITTER_CONSUMER_KEY: 'A2aGvbhWr08fphmKJE8iXC6DA'
    TWITTER_CONSUMER_SECRET: 'LVRGm9EXyemXOwyWdiVmNvVOGwDdNqATPUhw9rD1vqCrsEZd8n'
    TWITTER_ACCESS_TOKEN_KEY: '1264489447829233664-VKww2Hb174crgImR5I2QsuyFdkIJon'
    TWITTER_ACCESS_TOKEN_SECRET: 'PI73pqkveZWZoW4NsurYm225T6umiBzWKH42k1qKe1muP'

functions:
  index:
    handler: src/index.handler
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true