service: jsdailybot

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 256
  timeout: 30

functions:
  index:
    handler: src/index.handler
    events:
      - schedule: cron(39 19 * * ? *)